"""Canonical Omron BLE device profile catalog."""
from __future__ import annotations

from .const import MODERN_STACK_PARENT_SERVICE_UUID
from .devices import DeviceConfig, DeviceModelVariant

CANONICAL_DEVICE_PROFILES: dict[str, DeviceConfig] = {
    "HEM-6320T": DeviceConfig(
        model="HEM-6320T",
        endianness="big",
        user_start_addresses=[0x0370],
        per_user_records_count=[100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0F74,
        settings_write_address=0x0F9A,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_linear_10",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-6320T-Z", unverified=False),
        ),
    ),
    "HEM-6321T": DeviceConfig(
        model="HEM-6321T",
        endianness="big",
        user_start_addresses=[0x0370, 0x08E8],
        per_user_records_count=[100, 100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0F74,
        settings_write_address=0x0F9A,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_linear_10",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-6321T-Z", unverified=False),
        ),
    ),
    "HEM-6401T": DeviceConfig(
        model="HEM-6401T",
        endianness="little",
        # HEM-6401T exposes multiple data types; only the BP data_5 area is mapped here.
        user_start_addresses=[0x1350],
        per_user_records_count=[100],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0100,
        settings_write_address=0x0160,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x10, 0x20],
        time_sync_layout="eeprom_time_hem6401_prefix",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x06, "unread_counter_offset": 0x0E, "write_cursor_mask": 0xFFFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": 0},
            ],
        },
        record_parser="classic_vital_16_6401_family",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-6401T-Z", unverified=True, reason="fallback"),
            DeviceModelVariant("HEM-6402T-Z", unverified=True),
            DeviceModelVariant("HEM-6410T-Z", unverified=True),
        ),
    ),
    "HEM-7320T": DeviceConfig(
        model="HEM-7320T",
        endianness="big",
        user_start_addresses=[0x02AC, 0x05F4],
        per_user_records_count=[60, 60],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x0286,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_linear_10",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7320T-CA", unverified=False),
            DeviceModelVariant("HEM-7320T-CACS", unverified=False),
            DeviceModelVariant("HEM-7320T-ZV", unverified=False),
            DeviceModelVariant("HEM-7320T_TI-CA", unverified=False),
            DeviceModelVariant("HEM-7320T_TI-Z", unverified=False),
            DeviceModelVariant("HEM-8725T-WM", unverified=True, reason="fallback"),
        ),
    ),
    "HEM-7322T": DeviceConfig(
        model="HEM-7322T",
        legacy_pairing_workarounds=True,
        endianness="big",
        user_start_addresses=[0x02AC, 0x0824],
        per_user_records_count=[100, 100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x0286,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_linear_10",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14_7322_family",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7321T-CA", unverified=False),
            DeviceModelVariant("HEM-7321T_TI-CA", unverified=False),
            DeviceModelVariant("HEM-7321T_TI-Z", unverified=False),
            DeviceModelVariant("HEM-7280T-AP", unverified=False),
            DeviceModelVariant("HEM-7280T-E", unverified=False),
            DeviceModelVariant("HEM-7280T_TI-D", unverified=False),
            DeviceModelVariant("HEM-7280T_TI-E", unverified=False),
            DeviceModelVariant("HEM-7281T", unverified=False),
            DeviceModelVariant("HEM-7282T", unverified=False),
            DeviceModelVariant("HEM-7321T-ZV", unverified=False),
            DeviceModelVariant("HEM-7322T-D", unverified=False),
            DeviceModelVariant("HEM-7322T-E", unverified=False),
            DeviceModelVariant("HEM-7511T", unverified=True, reason="fallback"),
            DeviceModelVariant("HEM-8732K-SH", unverified=True, reason="fallback"),
            DeviceModelVariant("HEM-8732T-SH", unverified=True, reason="fallback"),
        ),
    ),
    "HEM-7600T": DeviceConfig(
        model="HEM-7600T",
        legacy_pairing_workarounds=True,
        endianness="big",
        user_start_addresses=[0x02AC],
        per_user_records_count=[100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x0286,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_linear_10",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7270C", unverified=False),
            DeviceModelVariant("HEM-7271T", unverified=False),
            DeviceModelVariant("HEM-7325T", unverified=False),
            DeviceModelVariant("HEM-7600T", unverified=False),
            DeviceModelVariant("HEM-7600T-E", unverified=False),
            DeviceModelVariant("HEM-7600T-Z", unverified=False),
            DeviceModelVariant("HEM-7600T-ZCD6BK", unverified=True),
            DeviceModelVariant("HEM-7600T-SH3BK", unverified=False),
            DeviceModelVariant("HEM-7600T2-JF", unverified=False),
            DeviceModelVariant("HEM-7600T_W", unverified=False),
            DeviceModelVariant("HEM-7600T_W-SH3W", unverified=False),
            DeviceModelVariant("HEM-7600T_W-Z", unverified=False),
            DeviceModelVariant("HEM-9601T-J3", unverified=True),
            DeviceModelVariant("HEM-9601T2-BR3", unverified=True),
            DeviceModelVariant("HEM-9601T_E3", unverified=True),
            DeviceModelVariant("HEM-9700T", unverified=True),
        ),
    ),
    "HEM-6232T": DeviceConfig(
        model="HEM-6232T",
        legacy_pairing_workarounds=True,
        endianness="big",
        user_start_addresses=[0x02E8, 0x0860],
        per_user_records_count=[100, 100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_classic_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14_6232_family",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-1026T2-AJC", unverified=True),
            DeviceModelVariant("HEM-1026T2-AJE", unverified=True),
            DeviceModelVariant("HEM-1026T2-AKA", unverified=True),
            DeviceModelVariant("HEM-6232T-AP", unverified=False),
            DeviceModelVariant("HEM-6232T-D", unverified=True),
            DeviceModelVariant("HEM-6232T-E", unverified=False),
            DeviceModelVariant("HEM-6232T-Z", unverified=True),
            DeviceModelVariant("HEM-6233T", unverified=False),
            DeviceModelVariant("HEM-6320T-SH", unverified=True),
            DeviceModelVariant("HEM-6322T-SH", unverified=True),
            DeviceModelVariant("HEM-6323T", unverified=True),
            DeviceModelVariant("HEM-6324T", unverified=True),
            DeviceModelVariant("HEM-6325T", unverified=True),
        ),
    ),
    "HEM-7530T": DeviceConfig(
        model="HEM-7530T",
        legacy_pairing_workarounds=True,
        endianness="big",
        user_start_addresses=[0x02E8],
        per_user_records_count=[90],
        record_byte_size=0x0E,
        transmission_block_size=0x10,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        # Unread counter unsupported; time sync follows [0x2C, 0x3C] layout
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 89, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-6161T-E", unverified=True),
            DeviceModelVariant("HEM-6161T-RU", unverified=True),
            DeviceModelVariant("HEM-6161T2-BR", unverified=True),
            DeviceModelVariant("HEM-6231T-SH", unverified=True),
            DeviceModelVariant("HEM-6231T_Z", unverified=True),
            DeviceModelVariant("HEM-6231T2-JC", unverified=False),
            DeviceModelVariant("HEM-6231T2-JE", unverified=False),
            DeviceModelVariant("HEM-6231T2-JT3", unverified=False),
            DeviceModelVariant("HEM-7136T-SH3", unverified=True),
            DeviceModelVariant("HEM-7138JT-SH", unverified=True),
            DeviceModelVariant("HEM-7138T-SH", unverified=True),
            DeviceModelVariant("HEM-7139T-SH3", unverified=True),
            DeviceModelVariant("HEM-7143T1-AIN", unverified=True),
            DeviceModelVariant("HEM-7143T1-AP", unverified=True),
            DeviceModelVariant("HEM-7143T1-D", unverified=True),
            DeviceModelVariant("HEM-7143T1-E", unverified=True),
            DeviceModelVariant("HEM-7143T1_D", unverified=True),
            DeviceModelVariant("HEM-7143T1_EBK", unverified=True),
            DeviceModelVariant("HEM-7143T2-E", unverified=True),
            DeviceModelVariant("HEM-7143T2_ESL", unverified=True),
            DeviceModelVariant("HEM-7144T1-AU", unverified=True),
            DeviceModelVariant("HEM-7144T2-BR", unverified=True),
            DeviceModelVariant("HEM-7144T2-LA", unverified=True),
            DeviceModelVariant("HEM-716DT2-LA", unverified=True),
            DeviceModelVariant("HEM-7271L-SH3", unverified=True),
            DeviceModelVariant("HEM-7271P-SH3", unverified=False),
            DeviceModelVariant("HEM-7271T_SH3", unverified=False),
            DeviceModelVariant("HEM-7530T-Z", unverified=True),
            DeviceModelVariant("HEM-7530T1-BR3", unverified=False),
            DeviceModelVariant("HEM-7530T_AP3", unverified=False),
            DeviceModelVariant("HEM-7530T_E3", unverified=False),
            DeviceModelVariant("HEM-7530T_J3", unverified=False),
            DeviceModelVariant("HEM-7530T_JT3", unverified=False),
            DeviceModelVariant("HEM-8630T-SH", unverified=False),
        ),
    ),
    "HEM-7150T": DeviceConfig(
        model="HEM-7150T",
        legacy_pairing_workarounds=True,
        endianness="little",
        user_start_addresses=[0x0098],
        per_user_records_count=[60],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7150T-CA", unverified=True),
            DeviceModelVariant("HEM-7150T-Z", unverified=False),
            DeviceModelVariant("HEM-7153JT_ASH", unverified=False),
            DeviceModelVariant("HEM-7153T_ASH", unverified=False),
            DeviceModelVariant("HEM-7156T-BR", unverified=False),
            DeviceModelVariant("HEM-7156T-LA", unverified=False),
            DeviceModelVariant("HEM-7156T_AAP", unverified=False),
            DeviceModelVariant("HEM-7156T_AP", unverified=False),
            DeviceModelVariant("HEM-7157T-AP", unverified=True),
            DeviceModelVariant("HEM-7158T-JC", unverified=True),
            DeviceModelVariant("HEM-7158T_AP3", unverified=True),
        ),
    ),
    # HEM-7151T: same layout as HEM-7150T but has 80 record slots
    "HEM-7151T": DeviceConfig(
        model="HEM-7151T",
        legacy_pairing_workarounds=True,
        endianness="little",
        user_start_addresses=[0x0098],
        per_user_records_count=[80],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 79, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7151T-Z", unverified=True),
        ),
    ),
    "HEM-7155T": DeviceConfig(
        model="HEM-7155T",
        legacy_pairing_workarounds=True,
        endianness="little",
        user_start_addresses=[0x0098, 0x0458],
        per_user_records_count=[60, 60],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7155T-ALRU", unverified=False),
            DeviceModelVariant("HEM-7155T-D", unverified=False),
            DeviceModelVariant("HEM-7155T-EBK", unverified=False),
            DeviceModelVariant("HEM-7155T_AP", unverified=False),
            DeviceModelVariant("HEM-7155T_ASH3BK", unverified=False),
            DeviceModelVariant("HEM-7155T_ASH3SL", unverified=False),
            DeviceModelVariant("HEM-7155T_ESL", unverified=False),
            DeviceModelVariant("HEM-7155T_K4-D", unverified=True),
            DeviceModelVariant("HEM-7155T_K4-EBK", unverified=True),
            DeviceModelVariant("HEM-7155T_K4-ESL", unverified=True),
            DeviceModelVariant("HEM-7340T-CA", unverified=True),
            DeviceModelVariant("HEM-7340T-Z", unverified=False),
            DeviceModelVariant("HEM-7340T_K4-CA", unverified=True),
            DeviceModelVariant("HEM-7340T_K4-Z", unverified=True),
            DeviceModelVariant("HEM-7341T-Z", unverified=False),
            DeviceModelVariant("HEM-7341T_K4-Z", unverified=True),
        ),
    ),
    # HEM-7155T modern stack V2 — OS bonding only, same EEPROM addresses as V1
    "HEM-7155T-MW": DeviceConfig(
        model="HEM-7155T-MW",
        parent_service_uuid=MODERN_STACK_PARENT_SERVICE_UUID,
        rx_channel_uuids=["49123040-aee8-11e1-a74d-0002a5d5c51b"],
        tx_channel_uuids=["db5b55e0-aee7-11e1-965e-0002a5d5c51b"],
        requires_unlock=False,
        supports_pairing=False,
        supports_os_bonding_only=True,
        endianness="little",
        user_start_addresses=[0x0098, 0x0458],
        per_user_records_count=[60, 60],
        record_byte_size=0x10,
        transmission_block_size=0x38,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=None,
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
    ),
    # HEM-7155T modern stack V3 — OS bonding only, different EEPROM addresses
    "HEM-7155T-MW3": DeviceConfig(
        model="HEM-7155T-MW3",
        parent_service_uuid=MODERN_STACK_PARENT_SERVICE_UUID,
        rx_channel_uuids=["49123040-aee8-11e1-a74d-0002a5d5c51b"],
        tx_channel_uuids=["db5b55e0-aee7-11e1-965e-0002a5d5c51b"],
        requires_unlock=False,
        supports_pairing=False,
        supports_os_bonding_only=True,
        endianness="little",
        user_start_addresses=[0x02E8, 0x06A8],
        per_user_records_count=[60, 60],
        record_byte_size=0x10,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=None,
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
    ),
    # HEM-7146T modern stack — OS bonding only, 1 user, 30 records
    "HEM-7146T": DeviceConfig(
        model="HEM-7146T",
        parent_service_uuid=MODERN_STACK_PARENT_SERVICE_UUID,
        rx_channel_uuids=["49123040-aee8-11e1-a74d-0002a5d5c51b"],
        tx_channel_uuids=["db5b55e0-aee7-11e1-965e-0002a5d5c51b"],
        requires_unlock=False,
        supports_pairing=False,
        supports_os_bonding_only=True,
        endianness="little",
        user_start_addresses=[0x02E8],
        per_user_records_count=[30],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 29, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7146T2-EBK", unverified=True),
            DeviceModelVariant("HEM-7146T2-ESL", unverified=True),
            DeviceModelVariant("HEM-7146T2-JD", unverified=True),
            DeviceModelVariant("HEM-7146T2-JF", unverified=True),
        ),
    ),
    "HEM-7342T": DeviceConfig(
        model="HEM-7342T",
        legacy_pairing_workarounds=True,
        endianness="little",
        user_start_addresses=[0x0098, 0x06D8],
        per_user_records_count=[100, 100],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7159T_AP3", unverified=False),
            DeviceModelVariant("HEM-7342T-CA", unverified=True),
            DeviceModelVariant("HEM-7342T-Z", unverified=False),
            DeviceModelVariant("HEM-7342T1-ACACD6", unverified=True),
            DeviceModelVariant("HEM-7343T-Z", unverified=False),
            DeviceModelVariant("HEM-7344JT_ASH3", unverified=False),
            DeviceModelVariant("HEM-7344T_ASH3BK", unverified=False),
            DeviceModelVariant("HEM-7344T_ASH3SL", unverified=False),
            DeviceModelVariant("HEM-7346T-AJC3", unverified=False),
            DeviceModelVariant("HEM-7346T-AJE3", unverified=False),
            DeviceModelVariant("HEM-7346T2-AJC32", unverified=False),
            DeviceModelVariant("HEM-7346T2-AJE32", unverified=False),
            DeviceModelVariant("HEM-7346T_ABR3", unverified=False),
            DeviceModelVariant("HEM-7346T_AP3", unverified=False),
            DeviceModelVariant("HEM-7347T-AJC3", unverified=False),
            DeviceModelVariant("HEM-7347T-AJE3", unverified=False),
            DeviceModelVariant("HEM-7347T2-AJC32", unverified=False),
            DeviceModelVariant("HEM-7347T2-AJE32", unverified=False),
            DeviceModelVariant("HEM-7349T_ABR", unverified=False),
            DeviceModelVariant("HEM-7361T-ALRU", unverified=False),
            DeviceModelVariant("HEM-7361T-AP", unverified=False),
            DeviceModelVariant("HEM-7361T-D", unverified=False),
            DeviceModelVariant("HEM-7361T-EBK", unverified=False),
            DeviceModelVariant("HEM-7361T1-BS", unverified=True),
            DeviceModelVariant("HEM-7361T_ESL", unverified=False),
        ),
    ),
    "HEM-7361T": DeviceConfig(
        model="HEM-7361T",
        legacy_pairing_workarounds=True,
        endianness="little",
        user_start_addresses=[0x0098, 0x06D8],
        per_user_records_count=[100, 100],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
    ),
    "HEM-7380T1": DeviceConfig(
        model="HEM-7380T1",
        parent_service_uuid=MODERN_STACK_PARENT_SERVICE_UUID,
        rx_channel_uuids=["49123040-aee8-11e1-a74d-0002a5d5c51b"],
        tx_channel_uuids=["db5b55e0-aee7-11e1-965e-0002a5d5c51b"],
        requires_unlock=False,
        supports_pairing=False,
        supports_os_bonding_only=True,
        endianness="little",
        user_start_addresses=[0x01C4, 0x0804],
        per_user_records_count=[100, 100],
        record_byte_size=0x10,
        transmission_block_size=0x38,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x18,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
        equivalent_model_ids=(
            
            DeviceModelVariant("HEM-7183T1-AP", unverified=True),
            DeviceModelVariant("HEM-7183T1-CAP", unverified=True),
            DeviceModelVariant("HEM-7183T1_FLBIN", unverified=True),
            DeviceModelVariant("HEM-7183T1_FLIN", unverified=True),
            DeviceModelVariant("HEM-7183T1_LAP", unverified=True),
            DeviceModelVariant("HEM-7188T1-LE", unverified=True),
            DeviceModelVariant("HEM-7188T1-LEO", unverified=True),
            DeviceModelVariant("HEM-7194T1-FLAP", unverified=True),
            DeviceModelVariant("HEM-7194T1-FLCAP", unverified=True),
            DeviceModelVariant("HEM-7194T1_FLBIN", unverified=True),
            DeviceModelVariant("HEM-7194T1_FLIN", unverified=True),
            DeviceModelVariant("HEM-7196T1-FLE", unverified=True),
            DeviceModelVariant("HEM-7196T1-FLEO", unverified=True),
            DeviceModelVariant("HEM-7376T1-ACACD6", unverified=True),
            DeviceModelVariant("HEM-7376T1-Z", unverified=True),
            DeviceModelVariant("HEM-7377T1-ZAZ", unverified=True),
            DeviceModelVariant("HEM-7380T", unverified=False),
            DeviceModelVariant("HEM-7380T1-EBK", unverified=False),
            DeviceModelVariant("HEM-7380T1-EOSL", unverified=True),
            DeviceModelVariant("HEM-7381T1-AZ", unverified=True),
            DeviceModelVariant("HEM-7382T1", unverified=False),   # same modern stack layout, confirmed by user report
            DeviceModelVariant("HEM-7382T1-AZAZ", unverified=True),
            DeviceModelVariant("HEM-7383T1-AP", unverified=False),
            DeviceModelVariant("HEM-7384T1-NBBR", unverified=False),
            DeviceModelVariant("HEM-7385T1-AJAZ3", unverified=True),
            DeviceModelVariant("HEM-7386T1-AJF3", unverified=True),
            DeviceModelVariant("HEM-7387T1-AJAZ3", unverified=True),
            DeviceModelVariant("HEM-7388T1-AJF3", unverified=True),
            DeviceModelVariant("HEM-7389T1-JM3", unverified=True),
        ),
    ),
    "HEM-7142T2": DeviceConfig(
        model="HEM-7142T2",
        parent_service_uuid=MODERN_STACK_PARENT_SERVICE_UUID,
        rx_channel_uuids=["49123040-aee8-11e1-a74d-0002a5d5c51b"],
        tx_channel_uuids=["db5b55e0-aee7-11e1-965e-0002a5d5c51b"],
        requires_unlock=False,
        supports_pairing=False,
        supports_os_bonding_only=True,
        endianness="little",
        # Single on-device measurement buffer region for this profile.
        user_start_addresses=[0x02E8],
        per_user_records_count=[14],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "backtrack_slots": 13,
            "collect_all_valid_in_index_window": True,
            "skip_full_scan_fallback_when_index_empty": True,
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 13, "slot_index_bias": -1},
            ],
            "record_addresses": [0x02E8],
            "record_byte_size": 0x0E,
            "record_step": 0x0E,
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
        equivalent_model_ids=(
            DeviceModelVariant("HEM-7138K-SH", unverified=False),
            DeviceModelVariant("HEM-7140T1-AP", unverified=False),
            DeviceModelVariant("HEM-7141T1-AP", unverified=False),
            DeviceModelVariant("HEM-7142T1-AP", unverified=False),
            DeviceModelVariant("HEM-7142T2-AP", unverified=False),
            DeviceModelVariant("HEM-7142T2-Z", unverified=True),
            DeviceModelVariant("HEM-7142T2-ZAZ", unverified=True),
            DeviceModelVariant("HEM-7142T2_JAZ", unverified=False),
            DeviceModelVariant("HEM-716BT2-ZAZ", unverified=True),
            DeviceModelVariant("HEM-716CT2-Z", unverified=True),
        ),
    ),
}
