"""Canonical Omron BLE device profile catalog."""
from __future__ import annotations

from .const import MODERN_STACK_PARENT_SERVICE_UUID
from .devices import DeviceConfig, HostPairingMode, UnlockMode

_MODERN_OS_BONDING_BASE = {
    "parent_service_uuid": MODERN_STACK_PARENT_SERVICE_UUID,
    "rx_channel_uuids": ["49123040-aee8-11e1-a74d-0002a5d5c51b"],
    "tx_channel_uuids": ["db5b55e0-aee7-11e1-965e-0002a5d5c51b"],
    "host_pairing_mode": HostPairingMode.OS_BONDING,
}

CANONICAL_DEVICE_PROFILES: dict[str, DeviceConfig] = {
    "HEM-6320T": DeviceConfig(
        model="HEM-6320T",
        endianness="big",
        user_start_addresses=[0x0370],
        per_user_records_count=[100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0F74,
        settings_write_address=0x0F9A,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_linear_10",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            "HEM-6320T-Z",
        ),
    ),
    "HEM-6321T": DeviceConfig(
        model="HEM-6321T",
        endianness="big",
        user_start_addresses=[0x0370, 0x08E8],
        per_user_records_count=[100, 100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0F74,
        settings_write_address=0x0F9A,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_linear_10",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            "HEM-6321T-Z",
        ),
    ),
    "HEM-6401T": DeviceConfig(
        model="HEM-6401T",
        endianness="little",
        # HEM-6401T exposes multiple data types; only the BP data_5 area is mapped here.
        user_start_addresses=[0x1350],
        per_user_records_count=[100],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0100,
        settings_write_address=0x0160,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x10, 0x20],
        time_sync_layout="eeprom_time_hem6401_prefix",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x06, "unread_counter_offset": 0x0E, "write_cursor_mask": 0xFFFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": 0},
            ],
        },
        record_parser="classic_vital_16_6401_family",
        equivalent_model_ids=(
            "HEM-6401T-Z",
            "HEM-6402T-Z",
            "HEM-6410T-Z",
        ),
    ),
    "HEM-7320T": DeviceConfig(
        model="HEM-7320T",
        endianness="big",
        user_start_addresses=[0x02AC, 0x05F4],
        per_user_records_count=[60, 60],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x0286,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_linear_10",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            "HEM-7320T-CA",
            "HEM-7320T-CACS",
            "HEM-7320T-ZV",
            "HEM-7320T_TI-CA",
            "HEM-7320T_TI-Z",
            "HEM-8725T-WM",
        ),
    ),
    "HEM-7322T": DeviceConfig(
        model="HEM-7322T",
        aggressive_gatt_timing=True,
        endianness="big",
        user_start_addresses=[0x02AC, 0x0824],
        per_user_records_count=[100, 100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x0286,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        time_sync_layout="eeprom_time_classic_mixed",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14_bitpacked",
        equivalent_model_ids=(
            "HEM-7321T-CA",
            "HEM-7321T_TI-CA",
            "HEM-7321T_TI-Z",
            "HEM-7280T-AP",
            "HEM-7280T-E",
            "HEM-7280T_TI-D",
            "HEM-7280T_TI-E",
            "HEM-7281T",
            "HEM-7282T",
            "HEM-7321T-ZV",
            "HEM-7322T-D",
            "HEM-7322T-E",
            "HEM-7511T",
            "HEM-8732K-SH",
            "HEM-8732T-SH",
        ),
    ),
    "HEM-7600T": DeviceConfig(
        model="HEM-7600T",
        aggressive_gatt_timing=True,
        endianness="big",
        user_start_addresses=[0x02AC],
        per_user_records_count=[100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x0286,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x14, 0x1E],
        # classic-mixed field order (confirmed from HEM-7600T-E EEPROM dumps)
        time_sync_layout="eeprom_time_classic_mixed",
        index_pointer_layout={
            "index_region_byte_size": 0x08,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        # bit-packed big-endian record layout (confirmed from HEM-7600T-E:
        # byte-aligned classic_vital_14 yielded dia>sys / bpm=26 / no date)
        record_parser="classic_vital_14_bitpacked",
        equivalent_model_ids=(
            "HEM-7270C",
            "HEM-7271T",
            "HEM-7325T",
            "HEM-7600T",
            "HEM-7600T-E",
            "HEM-7600T-Z",
            "HEM-7600T-ZCD6BK",
            "HEM-7600T-SH3BK",
            "HEM-7600T2-JF",
            "HEM-7600T_W",
            "HEM-7600T_W-SH3W",
            "HEM-7600T_W-Z",
            "HEM-9601T-J3",
            "HEM-9601T2-BR3",
            "HEM-9601T_E3",
            "HEM-9700T",
        ),
    ),
    "HEM-6232T": DeviceConfig(
        model="HEM-6232T",
        aggressive_gatt_timing=True,
        endianness="big",
        user_start_addresses=[0x02E8, 0x0860],
        per_user_records_count=[100, 100],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=[0x00, 0x08],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_classic_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14_6232_family",
        equivalent_model_ids=(
            "HEM-1026T2-AJC",
            "HEM-1026T2-AJE",
            "HEM-1026T2-AKA",
            "HEM-6232T-AP",
            "HEM-6232T-D",
            "HEM-6232T-E",
            "HEM-6232T-Z",
            "HEM-6233T",
            "HEM-6320T-SH",
            "HEM-6322T-SH",
            "HEM-6323T",
            "HEM-6324T",
            "HEM-6325T",
        ),
    ),
    "HEM-7530T": DeviceConfig(
        model="HEM-7530T",
        aggressive_gatt_timing=True,
        endianness="big",
        user_start_addresses=[0x02E8],
        per_user_records_count=[90],
        record_byte_size=0x0E,
        transmission_block_size=0x10,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        # Unread counter unsupported; time sync at [0x2C, 0x3C] uses classic offset8
        # field order (same 16-byte block as HEM-6232T, not modern linear order).
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_classic_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 89, "slot_index_bias": -1},
            ],
        },
        # bit-packed record layout (confirmed from HEM-6161T-RU; byte-aligned
        # classic_vital_14 yields bpm=26 and no valid datetime on this family).
        record_parser="classic_vital_14_bitpacked",
        equivalent_model_ids=(
            "HEM-6231T2-JC",
            "HEM-6231T2-JE",
            "HEM-6231T2-JT3",
            "HEM-7271P-SH3",
            "HEM-7271T_SH3",
            "HEM-7530T-Z",
            "HEM-7530T1-BR3",
            "HEM-7530T_AP3",
            "HEM-7530T_E3",
            "HEM-7530T_J3",
            "HEM-7530T_JT3",
            "HEM-8630T-SH",
        ),
    ),
    # Single-user 30-slot variant of the 7530T EEPROM family (0x260/0x2E8).
    "HEM-6161T": DeviceConfig(
        model="HEM-6161T",
        aggressive_gatt_timing=True,
        endianness="big",
        user_start_addresses=[0x02E8],
        per_user_records_count=[30],
        record_byte_size=0x0E,
        transmission_block_size=0x10,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_classic_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 29, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14_bitpacked",
        equivalent_model_ids=(
            "HEM-6161T-E",
            "HEM-6161T-RU",
            "HEM-6161T2-BR",
            "HEM-7271L-SH3",
        ),
    ),
    # Single-user 60-slot variant of the 7530T EEPROM family (0x260/0x2E8).
    "HEM-7136T": DeviceConfig(
        model="HEM-7136T",
        aggressive_gatt_timing=True,
        endianness="big",
        user_start_addresses=[0x02E8],
        per_user_records_count=[60],
        record_byte_size=0x0E,
        transmission_block_size=0x10,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_classic_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14_bitpacked",
        equivalent_model_ids=(
            "HEM-7136T-SH3",
            "HEM-7138JT-SH",
            "HEM-7138T-SH",
            "HEM-7139T-SH3",
        ),
    ),
    # Single-user 100-slot variant of the 7530T EEPROM family (0x260/0x2E8).
    "HEM-6231T": DeviceConfig(
        model="HEM-6231T",
        aggressive_gatt_timing=True,
        endianness="big",
        user_start_addresses=[0x02E8],
        per_user_records_count=[100],
        record_byte_size=0x0E,
        transmission_block_size=0x10,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_classic_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14_bitpacked",
        equivalent_model_ids=(
            "HEM-6231T-SH",
            "HEM-6231T_Z",
        ),
    ),
    "HEM-7150T": DeviceConfig(
        model="HEM-7150T",
        aggressive_gatt_timing=True,
        endianness="little",
        user_start_addresses=[0x0098],
        per_user_records_count=[60],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            "HEM-7150T-CA",
            "HEM-7150T-Z",
            "HEM-7153JT_ASH",
            "HEM-7153T_ASH",
            "HEM-7156T-BR",
            "HEM-7156T-LA",
            "HEM-7156T_AAP",
            "HEM-7156T_AP",
            "HEM-7157T-AP",
            "HEM-7158T-JC",
            "HEM-7158T_AP3",
        ),
    ),
    # HEM-7151T: same layout as HEM-7150T but has 80 record slots
    "HEM-7151T": DeviceConfig(
        model="HEM-7151T",
        aggressive_gatt_timing=True,
        endianness="little",
        user_start_addresses=[0x0098],
        per_user_records_count=[80],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 79, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            "HEM-7151T-Z",
        ),
    ),
    "HEM-7155T": DeviceConfig(
        model="HEM-7155T",
        aggressive_gatt_timing=True,
        endianness="little",
        user_start_addresses=[0x0098, 0x0458],
        per_user_records_count=[60, 60],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            "HEM-7155T-ALRU",
            "HEM-7155T-D",
            "HEM-7155T-EBK",
            "HEM-7155T-EBL",
            "HEM-7155T_AP",
            "HEM-7155T_ASH3BK",
            "HEM-7155T_ASH3SL",
            "HEM-7340T-CA",
            "HEM-7340T-Z",
            "HEM-7341T-Z",
        ),
    ),
    # HEM-7155T modern stack V2 — OS bonding only, same EEPROM addresses as V1
    "HEM-7155T-MW": DeviceConfig(
        **_MODERN_OS_BONDING_BASE,
        model="HEM-7155T-MW",
        unlock_mode=UnlockMode.NONE,
        endianness="little",
        user_start_addresses=[0x0098, 0x0458],
        per_user_records_count=[60, 60],
        record_byte_size=0x10,
        transmission_block_size=0x38,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=None,
        # EEPROM time sync confirmed via omblepy hem-7155t.py (settings block at
        # 0x0010, time bytes [0x2C, 0x3C], modern offset8 layout). Addresses
        # match the classic HEM-7155T V1 profile exactly.
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
    ),
    # HEM-7155T K4 — modern stack, MW3 EEPROM layout, no secure session.
    "HEM-7155T-K4": DeviceConfig(
        **_MODERN_OS_BONDING_BASE,
        model="HEM-7155T-K4",
        unlock_mode=UnlockMode.NONE,
        endianness="little",
        user_start_addresses=[0x02E8, 0x06A8],
        per_user_records_count=[60, 60],
        record_byte_size=0x10,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
        equivalent_model_ids=(
            "HEM-7155T_K4-D",
            "HEM-7155T_K4-EBK",
            "HEM-7155T_K4-ESL",
            "HEM-7340T_K4-CA",
            "HEM-7340T_K4-Z",
            "HEM-7341T_K4-Z",
        ),
    ),
    # HEM-7155T modern stack V3 — OS bonding + stateless token handshake.
    # Confirmed via HCI btsnoop of HEM-7155T-ESL ("X4 Smart"): a Just Works bond
    # plus a 0x11/0x91 token handshake (host sends 0x11 + 4 nonce bytes, device
    # echoes them in a 0x91 0x00 ack), then plaintext 08-frame memory protocol
    # with XOR CRC — NOT the app-layer secure session (no ECDH/AES-CCM).
    # The token is required for memory access outside the device's -P- pairing
    # grace window: a normal-mode poll without it returns no data.
    "HEM-7155T-MW3": DeviceConfig(
        **_MODERN_OS_BONDING_BASE,
        model="HEM-7155T-MW3",
        unlock_mode=UnlockMode.TOKEN_KEY,
        endianness="little",
        user_start_addresses=[0x02E8, 0x06A8],
        per_user_records_count=[60, 60],
        record_byte_size=0x10,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        # EEPROM time sync: the V3 settings block moved to 0x0260, but the
        # time-bytes slice [0x2C, 0x3C] is a block-relative offset (same as the
        # 7155T family) so it applies unchanged. EEPROM sync runs before CTS and
        # falls back to it, so CTS still works if these offsets are wrong.
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 59, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
        equivalent_model_ids=(
            # HEM-7155T_ESL / HEM-7155T-ESLI ("X4 Smart"): modern FE4A stack with
            # V3 EEPROM at 0x0260, but classic plaintext transport over a Just
            # Works bond (NOT secure session) — confirmed via HCI btsnoop.
            "HEM-7155T_ESL",
        ),
    ),
    # HEM-7146T modern stack — OS bonding only, 1 user, 30 records
    "HEM-7146T": DeviceConfig(
        **_MODERN_OS_BONDING_BASE,
        model="HEM-7146T",
        unlock_mode=UnlockMode.NONE,
        endianness="little",
        user_start_addresses=[0x02E8],
        per_user_records_count=[30],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 29, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
        equivalent_model_ids=(
            "HEM-7143T1-AIN",
            "HEM-7143T1-AP",
            "HEM-7143T1-D",
            "HEM-7143T1-E",
            "HEM-7143T1_D",
            "HEM-7143T1_EBK",
            "HEM-7143T2-E",
            "HEM-7143T2_ESL",
            "HEM-7144T1-AU",
            "HEM-7144T2-BR",
            "HEM-7144T2-LA",
            "HEM-7146T2-EBK",
            "HEM-7146T2-ESL",
            "HEM-7146T2-JD",
            "HEM-7146T2-JF",
            "HEM-716DT2-LA",
        ),
    ),
    "HEM-7342T": DeviceConfig(
        model="HEM-7342T",
        aggressive_gatt_timing=True,
        endianness="little",
        user_start_addresses=[0x0098, 0x06D8],
        per_user_records_count=[100, 100],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        equivalent_model_ids=(
            "HEM-7159T_AP3",
            "HEM-7342T-CA",
            "HEM-7342T-Z",
            "HEM-7342T1-ACACD6",
            "HEM-7343T-Z",
            "HEM-7344JT_ASH3",
            "HEM-7344T_ASH3BK",
            "HEM-7344T_ASH3SL",
            "HEM-7346T-AJC3",
            "HEM-7346T-AJE3",
            "HEM-7346T2-AJC32",
            "HEM-7346T2-AJE32",
            "HEM-7346T_ABR3",
            "HEM-7346T_AP3",
            "HEM-7347T-AJC3",
            "HEM-7347T-AJE3",
            "HEM-7347T2-AJC32",
            "HEM-7347T2-AJE32",
            "HEM-7349T_ABR",
            "HEM-7361T-ALRU",
            "HEM-7361T-AP",
            "HEM-7361T-D",
            "HEM-7361T-EBK",
            "HEM-7361T1-BS",
            "HEM-7361T_ESL",
        ),
    ),
    "HEM-7361T": DeviceConfig(
        model="HEM-7361T",
        aggressive_gatt_timing=True,
        endianness="little",
        user_start_addresses=[0x0098, 0x06D8],
        per_user_records_count=[100, 100],
        record_byte_size=0x10,
        transmission_block_size=0x10,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=[0x00, 0x10],
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
    ),
    "HEM-7380T1": DeviceConfig(
        **_MODERN_OS_BONDING_BASE,
        model="HEM-7380T1",
        unlock_mode=UnlockMode.SECURE_SESSION,
        endianness="little",
        user_start_addresses=[0x01C4, 0x0804],
        per_user_records_count=[100, 100],
        record_byte_size=0x10,
        transmission_block_size=0x38,
        settings_read_address=0x0010,
        settings_write_address=0x0054,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x18,
            "endianness": "little",
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
                {"write_cursor_offset": 0x02, "unread_counter_offset": 0x06, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 99, "slot_index_bias": -1},
            ],
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
        equivalent_model_ids=(
            "HEM-7183T1-AP",
            "HEM-7183T1-CAP",
            "HEM-7183T1_FLBIN",
            "HEM-7183T1_FLIN",
            "HEM-7183T1_LAP",
            "HEM-7188T1-LE",
            "HEM-7188T1-LEO",
            # HEM-7194T1 / HEM-7196T1 family shares this modern-stack profile
            # (OS bonding, FE4A parent service, same TX/RX UUIDs and EEPROM layout).
            "HEM-7194T1-FLAP",
            "HEM-7194T1-FLCAP",
            "HEM-7194T1_FLBIN",
            "HEM-7194T1_FLIN",
            "HEM-7196T1-FLE",
            "HEM-7196T1-FLEO",
            "HEM-7376T1-ACACD6",
            "HEM-7376T1-Z",
            "HEM-7377T1-ZAZ",
            "HEM-7380T",
            "HEM-7380T1-EBK",
            "HEM-7380T1-EOSL",
            "HEM-7381T1-AZ",
            "HEM-7382T1",   # same modern stack layout, confirmed by user report
            "HEM-7382T1-AZAZ",
            "HEM-7383T1-AP",
            "HEM-7384T1-NBBR",
            "HEM-7385T1-AJAZ3",
            "HEM-7386T1-AJF3",
            "HEM-7387T1-AJAZ3",
            "HEM-7388T1-AJF3",
            "HEM-7389T1-JM3",
        ),
    ),
    # HEM-7142T2 — modern stack, MW3-style EEPROM, stateless 0x11/0x91 token
    # handshake (same pattern as HEM-7155T-MW3; confirmed via HCI btsnoop).
    "HEM-7142T2": DeviceConfig(
        **_MODERN_OS_BONDING_BASE,
        model="HEM-7142T2",
        unlock_mode=UnlockMode.TOKEN_KEY,
        endianness="little",
        # Single on-device measurement buffer region for this profile.
        user_start_addresses=[0x02E8],
        per_user_records_count=[14],
        record_byte_size=0x0E,
        transmission_block_size=0x38,
        settings_read_address=0x0260,
        settings_write_address=0x02A4,
        settings_unread_records_bytes=None,
        settings_time_sync_bytes=[0x2C, 0x3C],
        time_sync_layout="eeprom_time_modern_offset8",
        index_pointer_layout={
            "index_region_byte_size": 0x10,
            "endianness": "big",
            "backtrack_slots": 13,
            "collect_all_valid_in_index_window": True,
            "skip_full_scan_fallback_when_index_empty": True,
            "users": [
                {"write_cursor_offset": 0x00, "unread_counter_offset": 0x04, "write_cursor_mask": 0xFF, "slot_index_min": 0, "slot_index_max": 13, "slot_index_bias": -1},
            ],
            "record_addresses": [0x02E8],
            "record_byte_size": 0x0E,
            "record_step": 0x0E,
        },
        record_parser="classic_vital_14",
        prefer_latest_by_slot_index=True,
        equivalent_model_ids=(
            "HEM-7138K-SH",
            "HEM-7140T1-AP",
            "HEM-7141T1-AP",
            "HEM-7142T1-AP",
            "HEM-7142T2-AP",
            "HEM-7142T2-Z",
            "HEM-7142T2-ZAZ",
            "HEM-7142T2_JAZ",
            "HEM-716BT2-ZAZ",
            "HEM-716CT2-Z",
        ),
    ),
}
